name: srs

services:
  srs:
    image: ossrs/srs:v6.0-r0
    container_name: srs-balance
    ports:
      - "1935:1935"
      - "8080:8080"
      - "10080:10080/udp"
    volumes:
      - ./outdoor_balance.txt:/usr/local/srs/conf/srt.conf
    command: ./objs/srs -c conf/srt.conf
